In [16]:
# !pip install kagglehub

In [14]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "ai_smart_manufacturing_predictive_maintenance.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "mobeenfatimah/smart-factory-predictive-maintenance-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

display(df.head())

C:\Users\HP\AppData\Local\Temp\ipykernel_17708\3733586091.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

,machine_id,monitoring_id,timestamp,factory_id,production_line,machine_type,manufacturer,model,installation_year,machine_age,...,vibration_anomaly_score,pressure_anomaly_score,electrical_anomaly_score,energy_anomaly_score,machine_health_score,failure_probability,maintenance_priority,remaining_useful_life_hours,failure_type,machine_failure
0,MCH-00001,MON-100000,2026-03-02 02:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,8.6,15.4,9.0,54.1,80.6,0.4,Low,14591,Mechanical Failure,1
1,MCH-00001,MON-100001,2026-03-02 05:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,17.5,9.8,0.3,44.7,80.6,0.4,Low,14363,No Failure,0
2,MCH-00001,MON-100002,2026-03-02 06:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,10.7,30.8,3.1,47.2,80.6,0.4,Low,14639,No Failure,0
3,MCH-00001,MON-100003,2026-03-02 12:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,11.2,14.5,13.8,51.7,80.5,0.5,Low,14459,No Failure,0
4,MCH-00001,MON-100004,2026-03-02 16:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,22.3,8.6,9.3,52.2,80.5,0.5,Low,14670,No Failure,0

In [15]:
df.columns

Index(['machine_id', 'monitoring_id', 'timestamp', 'factory_id',
       'production_line', 'machine_type', 'manufacturer', 'model',
       'installation_year', 'machine_age', 'machine_capacity',
       'machine_power_kw', 'machine_weight_kg', 'temperature_c',
       'vibration_mm_s', 'pressure_bar', 'rotational_speed_rpm', 'torque_nm',
       'voltage_v', 'current_a', 'power_consumption_kw', 'humidity_percent',
       'acoustic_level_db', 'bearing_temperature_c', 'motor_temperature_c',
       'oil_temperature_c', 'coolant_temperature_c', 'oil_pressure_bar',
       'hydraulic_pressure_bar', 'air_pressure_bar', 'operating_hours',
       'idle_hours', 'production_cycles', 'load_percentage', 'production_rate',
       'downtime_hours', 'shift_hours', 'energy_consumption_kwh',
       'ambient_temperature_c', 'ambient_humidity_percent', 'dust_level',
       'air_quality_index', 'noise_level_db', 'factory_shift',
       'last_maintenance_date', 'days_since_maintenance', 'maintenance_count',
       'maintenance_cost', 'last_repair_duration_hours',
       'replacement_parts_count', 'technician_experience_years',
       'maintenance_type', 'previous_failure_count',
       'days_since_previous_failure', 'failure_frequency', 'bearing_health',
       'motor_health', 'pump_health', 'hydraulic_health', 'electrical_health',
       'cooling_system_health', 'temperature_anomaly_score',
       'vibration_anomaly_score', 'pressure_anomaly_score',
       'electrical_anomaly_score', 'energy_anomaly_score',
       'machine_health_score', 'failure_probability', 'maintenance_priority',
       'remaining_useful_life_hours', 'failure_type', 'machine_failure'],
      dtype='str')

In [17]:
feature = ['machine_id', 'monitoring_id', 'timestamp', 'factory_id',
       'production_line', 'machine_type', 'manufacturer', 'model',
       'installation_year', 'machine_age', 'machine_capacity',
       'machine_power_kw', 'machine_weight_kg', 'temperature_c',
       'vibration_mm_s', 'pressure_bar', 'rotational_speed_rpm', 'torque_nm',
       'voltage_v', 'current_a', 'power_consumption_kw', 'humidity_percent',
       'acoustic_level_db', 'bearing_temperature_c', 'motor_temperature_c',
       'oil_temperature_c', 'coolant_temperature_c', 'oil_pressure_bar',
       'hydraulic_pressure_bar', 'air_pressure_bar', 'operating_hours',
       'idle_hours', 'production_cycles', 'load_percentage', 'production_rate',
       'downtime_hours', 'shift_hours', 'energy_consumption_kwh',
       'ambient_temperature_c', 'ambient_humidity_percent', 'dust_level',
       'air_quality_index', 'noise_level_db', 'factory_shift',
       'last_maintenance_date', 'days_since_maintenance', 'maintenance_count',
       'maintenance_cost', 'last_repair_duration_hours',
       'replacement_parts_count', 'technician_experience_years',
       'maintenance_type', 'previous_failure_count',
       'days_since_previous_failure', 'failure_frequency', 'bearing_health',
       'motor_health', 'pump_health', 'hydraulic_health', 'electrical_health',
       'cooling_system_health', 'temperature_anomaly_score',
       'vibration_anomaly_score', 'pressure_anomaly_score',
       'electrical_anomaly_score', 'energy_anomaly_score',
       'machine_health_score', 'failure_probability', 'maintenance_priority',
       'remaining_useful_life_hours', 'failure_type']

In [19]:
x = df[feature]
y = df['machine_failure']

In [20]:
display(x.head())

,machine_id,monitoring_id,timestamp,factory_id,production_line,machine_type,manufacturer,model,installation_year,machine_age,...,temperature_anomaly_score,vibration_anomaly_score,pressure_anomaly_score,electrical_anomaly_score,energy_anomaly_score,machine_health_score,failure_probability,maintenance_priority,remaining_useful_life_hours,failure_type
0,MCH-00001,MON-100000,2026-03-02 02:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,38.4,8.6,15.4,9.0,54.1,80.6,0.4,Low,14591,Mechanical Failure
1,MCH-00001,MON-100001,2026-03-02 05:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,44.1,17.5,9.8,0.3,44.7,80.6,0.4,Low,14363,No Failure
2,MCH-00001,MON-100002,2026-03-02 06:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,38.3,10.7,30.8,3.1,47.2,80.6,0.4,Low,14639,No Failure
3,MCH-00001,MON-100003,2026-03-02 12:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,40.5,11.2,14.5,13.8,51.7,80.5,0.5,Low,14459,No Failure
4,MCH-00001,MON-100004,2026-03-02 16:00:00,FAC-03,LINE-02,Milling Machine,Fanuc,MOD-839,2022,4,...,32.7,22.3,8.6,9.3,52.2,80.5,0.5,Low,14670,No Failure

In [25]:
df.describe()

,installation_year,machine_age,machine_capacity,machine_power_kw,machine_weight_kg,temperature_c,vibration_mm_s,pressure_bar,rotational_speed_rpm,torque_nm,...,cooling_system_health,temperature_anomaly_score,vibration_anomaly_score,pressure_anomaly_score,electrical_anomaly_score,energy_anomaly_score,machine_health_score,failure_probability,remaining_useful_life_hours,machine_failure
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000
mean,2017.479200,8.520800,279.227480,103.285740,4245.295620,63.137905,3.535235,7.506587,1835.785730,224.429348,...,79.589381,38.568392,30.357078,17.378869,6.343796,50.000821,76.441434,1.340028,13388.959510,0.01472
std,3.482885,3.482885,129.492878,54.197245,2163.942919,6.156372,0.990613,1.391559,151.553392,36.784446,...,11.567936,10.684820,10.360160,12.443269,6.570912,3.256658,5.147489,1.434786,1365.264052,0.12043
min,2012.000000,3.000000,50.000000,10.000000,500.000000,41.900000,0.720000,2.520000,1177.000000,69.500000,...,59.200000,0.500000,0.000000,0.000000,0.000000,32.000000,58.900000,0.100000,8856.000000,0.00000
25%,2014.000000,5.000000,168.575000,56.300000,2353.275000,58.500000,2.730000,6.480000,1733.000000,199.500000,...,69.700000,30.700000,22.300000,7.300000,1.300000,47.900000,72.900000,0.400000,12428.000000,0.00000
50%,2017.000000,9.000000,280.500000,103.350000,4251.100000,63.200000,3.530000,7.500000,1837.000000,224.900000,...,79.300000,38.600000,30.400000,15.400000,4.600000,50.000000,76.400000,0.900000,13364.000000,0.00000
75%,2021.000000,12.000000,389.500000,148.725000,6116.700000,67.800000,4.340000,8.540000,1941.000000,250.100000,...,89.700000,46.600000,38.400000,25.500000,9.200000,52.100000,80.100000,1.700000,14336.000000,0.00000
max,2023.000000,14.000000,500.000000,199.900000,7998.400000,80.900000,6.210000,11.700000,2230.000000,310.800000,...,100.000000,74.600000,63.800000,68.100000,56.300000,68.800000,94.300000,14.500000,18909.000000,1.00000

In [29]:
print(df['machine_age'].dtypes)

int64

In [28]:
display(df.dtypes)

machine_id                         str
monitoring_id                      str
timestamp                          str
factory_id                         str
production_line                    str
                                ...
failure_probability            float64
maintenance_priority               str
remaining_useful_life_hours      int64
failure_type                       str
machine_failure                  int64
Length: 72, dtype: object

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [23]:
from sklearn.svm import SVC

In [24]:
model = SVC()
model.fit(x_train, y_train)
predict = model.predict(x_test)

ValueError: could not convert string to float: 'MCH-02561'